haugene/docker-transmission-openvpn

- README.md
Will help resolve a number of queries. 
Shutting down #19 #20 with this PR
> Minor update to readme issues section

- README.md
To be more precise and accessible for everyone :)
> Added one missing command

- Dockerfile
This pulls the updated TorGuard Configuration from their servers and
configures it for this image
> Pull Updated TorGuard Configuration

- openvpn/smartvpn/default.ovpn
- openvpn/smartvpn/smartvpn-de001.ovpn
- openvpn/smartvpn/smartvpn-nl001.ovpn
Think this should work for #124
> Added smartvpn provider

- docker-compose-armhf.yml
- docker-compose.yml
Please check this to see if it fixes #162
> Updated compose files to match documentation and fix #162

- README.md
I was left a bit confused by the readme on how to set openvpn configuration. I eventually just had to inspect start.sh to see what you were doing. So I thought I would help with the README about this.
Works like a charm, by the way =).
> Clarify OPENVPN_CONFIG Settings in README

- openvpn/integrityvpn/default.ovpn
New settings downloaded from https://integrity.st/download/Integrity_v3.tblk.zip (2017-04-15) (SHA256 e340d04a047915e859a4d68923489ca42b851a8fd2930f230f233875a7fb7eed)
> Updated provider Bahnhof Integrity VPN.

- Dockerfile
Pretty straight forward.  I did notice that transmission is storing/looking for stuff in a slight different place. Pretty sure this a transmission change between versions.
Thanks again for publishing this.
> Ok, upgraded to 16.04,

- openvpn/anonvpn/Chicago.ovpn
- openvpn/anonvpn/Frankfurt.ovpn
- openvpn/anonvpn/London.ovpn
- openvpn/anonvpn/Miami.ovpn
- openvpn/anonvpn/New_York.ovpn
- openvpn/anonvpn/Seattle.ovpn
- openvpn/anonvpn/Toronto.ovpn
- openvpn/anonvpn/default.ovpn
- openvpn/anonvpn/source.txt
added 7 profiles for Anonvpn.io. I originally was given these profiles as part of a help desk response, so I'm not sure if they are public knowledge.
> VPN configuration for anonvpn

- README.md
To avoid issue with latest version of Synology's Docker package 17.05.0
> Command line for synology: add --sysctl

- Dockerfile.armhf
A simple update of dockerize made this work for me. 
Should resolve #294
> Upgrading dockerize and required packages

- openvpn/slickvpn/Canada-Toronto.ovpn
Trying out adding all hostnames AND additional ports
> Modifying SlickVPN config for Toronto

- openvpn/slickvpn/Netherlands.ovpn
> Modify Netherlands OVPN config for SlickVPN

- openvpn/ovpn/US.ovpn
Automatically chooses between Los Angeles, CA and Miami, FL servers
> Add US OVPN.com servers

- Dockerfile
- Dockerfile.alpine
- Dockerfile.armhf
- README.md
- transmission/start.sh
This is based upon the project https://github.com/ronggang/transmission-web-control/
> feat(web-ui): add transmission-web-control UI

- Dockerfile
- transmission/start.sh
- transmission/updatePPPort.sh
see: https://www.perfect-privacy.com/faq/ section "How are the default forwarding ports being calculated?"
> add perfect privacy port forwarding

- openvpn/tunnelDown.sh
- openvpn/tunnelUp.sh
Suggestion made by @firecat53 on [this issue](https://github.com/haugene/docker-transmission-openvpn/issues/475) to fix it
> Fix issue 475

- README.md
Added information on how to connect to RPC.
> Update README.MD with instructions for RPC

- Dockerfile
- Dockerfile.alpine
- Dockerfile.armhf
Added symlinks to allow original ui button to work /w transmission-web-control. Without these, the button does not function as index.original.html does not exist. Had to create link to thje javascript files etc... or it did not function properly.
Tested under https://hub.docker.com/r/dulanic/docker-transmission-openvpn
> Add links to allow tr-web-control to use original ui button.

- DockerfileCrossBuild.armhf
- README.md
- docker-compose-armhf.yml
- plugins/rss/DockerfileCrossBuild.armhf
- proxy/DockerfileCrossBuild.armhf
Fix #638.
@haugene The Dockerfile location in Docker Hub settings will need to be updated to `DockerfileCrossBuild.armhf` for all `armhf` tags
> Fix builds on ARM arch but keeping ARM cross builds.

- openvpn/tiger/AT Vienna.ovpn
- openvpn/tiger/CA Montreal.ovpn
- openvpn/tiger/CA Toronto.ovpn
- openvpn/tiger/CH Zurich.ovpn
- openvpn/tiger/DK Copenhagen.ovpn
- openvpn/tiger/ES Madrid.ovpn
- openvpn/tiger/Frankfurt.ovpn
- openvpn/tiger/GB London.ovpn
- openvpn/tiger/NL Amsterdam.ovpn
- openvpn/tiger/NO Oslo.ovpn
- openvpn/tiger/RO Bucharest.ovpn
- openvpn/tiger/US Atlanta.ovpn
- openvpn/tiger/US Denver.ovpn
- openvpn/tiger/US Los Angeles.ovpn
- openvpn/tiger/US Miami.ovpn
- openvpn/tiger/US New York.ovpn
This PR updates all of the `.ovpn` configs for tigervpn - which I solved #718 for me.
> Update .ovpn configs for tigervpn

- openvpn/nordvpn/updateConfigs.sh
- openvpn/start.sh
NORDVPN_PROTOCOL wasn't being set correctly when an OPENVPN_CONFIG was provided. Now fixed.
> Fix for automatic setting of NORDVPN_PROTOCOL

- openvpn/protonvpn/se.protonvpn.com.udp.ovpn
- openvpn/protonvpn/sg.protonvpn.com.udp.ovpn
ProtonVPN recently added country configs that allow you to select a country and they will pick the fastest server. Easier than swapping configs.
> Adding ProtonVPN Country Configs

- openvpn/pia/AU Perth.ovpn
PIA now has an Australia Perth location
> Add AU Perth

- openvpn/nordvpn/updateConfigs.sh
See issue #867 for a more in depth explanation
> Fixed nordvpn config download function

- Dockerfile.armhf
Adding the scripts/healthcheck.sh will make health check work on armhf based systems.
> Added healthcheck for armhf systems

- Dockerfile
- Dockerfile.alpine
Updates:
- `ubuntu:16.04` -> `ubuntu:18.04`
- `alpine:3.8` -> `alpine:3.10`
This should also fix #936.
> Update docker base images

- openvpn/protonvpn/ch-gr-01.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-01.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-02.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-03.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-04.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-05.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-06.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-07.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr-08.protonvpn.com.udp.ovpn
- openvpn/protonvpn/gr.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-01.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-02.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-03.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-04.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-05.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-06.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-07.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt-08.protonvpn.com.udp.ovpn
- openvpn/protonvpn/lt.protonvpn.com.udp.ovpn
- openvpn/protonvpn/se-lt-01.protonvpn.com.udp.ovpn
ProtonVPN opened servers in Greece. These are the certificates with the correct `auth-user-pass /config/openvpn-credentials.txt` references.
> New ProtonVPN servers in Greece+Lithuania+Estonia+Serbia

- docs/nordvpn-script.md
I was looking through the docs for these environment variables and glazed right past them due to them not being in a markdown table. So I made that table. I am unable to comment or format the rest of the docs because I am not aware of the implementation.
> Prettify NordVPN docs page

- openvpn/tiger/AT Klagenfurt.ovpn
- openvpn/tiger/BG Sofia.ovpn
- openvpn/tiger/CA Vancouver.ovpn
- openvpn/tiger/CZ Prague.ovpn
- openvpn/tiger/DE Cologne.ovpn
- openvpn/tiger/DE Frankfurt.ovpn
- openvpn/tiger/DE Munich.ovpn
- openvpn/tiger/FR Paris.ovpn
- openvpn/tiger/GB Manchester.ovpn
- openvpn/tiger/HU Budapest.ovpn
- openvpn/tiger/IE Dublin.ovpn
- openvpn/tiger/IT Milan.ovpn
- openvpn/tiger/IT Palermo.ovpn
- openvpn/tiger/LU Luxembourg.ovpn
- openvpn/tiger/RS Belgrade.ovpn
- openvpn/tiger/RU Moscow.ovpn
- openvpn/tiger/RU St. Petersburg.ovpn
- openvpn/tiger/SE Stockholm.ovpn
- openvpn/tiger/SI Ljubljana.ovpn
- openvpn/tiger/SK Bratislava.ovpn
- openvpn/tiger/TR Ankara.ovpn
- openvpn/tiger/TR Istanbul.ovpn
- openvpn/tiger/UA Kiev.ovpn
- openvpn/tiger/US Chicago.ovpn
- openvpn/tiger/US Seattle.ovpn
- openvpn/tiger/default.ovpn
New pull request because I screwed up merging the previous commits.
> Add additional tigervpn config files and set default to "DE Frankfurt"

- openvpn/start.sh
- openvpn/updateFreeVPN.sh
- Using "me" as default FreeVPN domain
- launched updateFreeVPN.sh during start.sh
- added  updateFreeVPN.sh to a daily cron
- changed updateFreeVPN.sh to use OPENVPN_CONFIG domain
- fix issue on unzip into non existent folder
- searching and changing oven file names accordingly to latest bundle (April 2020) obtained on .me domain
Thank you for this awesome docker image.
> Auto update freevpn

- docs/supported-providers.md
Update documentation to include missing supported providers
> Add missing supported providers

- openvpn/fastestvpn/default.ovpn
> Fixed fastestvpn default.ovpn symlink

- openvpn/protonvpn/default.ovpn
fixes missing default
fix #1173
> Added default.ovpn to protonvpn

- Dockerfile.alpine
Missed this when fixing tinyproxy on alpine
> Fixed missing openrc on alpine for tinyproxy

- scripts/healthcheck.sh
PR fixes status check for transmission & openvpn daemons in healthcheck.
> healthcheck

- plugins/rss/Dockerfile
- plugins/rss/Dockerfile.armhf
- plugins/rss/DockerfileCrossBuild.armhf
- plugins/rss/environment-variables.tmpl
- plugins/rss/start.sh
- plugins/rss/transmission-rss.tmpl
adds support for  regexp, resolve #1167
> Adds regexp support to rss

- scripts/healthcheck.sh
> Exclude grep from ps -ef result

- openvpn/ovpn/Sweden.ovpn
Fixes issue https://github.com/haugene/docker-transmission-openvpn/issues/1282
> Fixed remote hosts in Sweden.ovpn

- Dockerfile.alpine
> Updated ufw testing url

- openvpn/start.sh
> Fix for invalid URLs generated when setting OPENVPN_CONFIG 

- openvpn/tunnelDown.sh
- scripts/healthcheck.sh
I added some code to try recovering from a hung TUN by resetting it.
See issue #1306
> Update HealthCheck for auto-recover TUN down

- README.md
Fixed a small spelling mistake in the readme.
> Fixed spelling mistake in readme

- openvpn/pia/update-port.sh
Issue found in #1479 
Snippet:
Ports are good for 2 months. So we check every 30 minutes if the port is still open. We send a curl and get a reply.  PIA does every 15 minutes (they say this is the inactivity timeframe where you could get booted off the port).   
Since tokens expire every 24 hours, our port ownership is tied to the payload and signature we got when we bound to the port.
**But check this out** (from our update-ports.sh)
```
echo "token expiry $pf_token_expiry"                                              
pf_remaining=$((  $pf_token_expiry - $(date +%s) ))
Output:
token expiry 1610289885 
remaining = 5425148
```
English:
Token expiration: In 24 hours
Remaining: 62 days
The problem:
```
while true; do
pf_remaining=$((  $pf_token_expiry - $(date +%s) ))
```
We're using the …
> PIA port binding time - Fix for #1601.  See #1479 for discovery

- .circleci/config.yml
Reverts haugene/docker-transmission-openvpn#1671
> Revert "add ghcr publish"

- .circleci/config.yml
Reverts haugene/docker-transmission-openvpn#1676
> Revert "Revert "add ghcr publish""

- docs/config-options.md
Per https://github.com/haugene/docker-transmission-openvpn/issues/1734
> Correct the github hyperlink for Flood Web UI

- .github/ISSUE_TEMPLATE/add-or-update-provider.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/issue-template-check.yml
As per your suggestion @pkishino. Adding the workflow to close new issues if they don't follow the templates.
Had to change the templates from `**headline**` to `## headline` as that is what it compares in the .md files.
May this bring forth better issues :crossed_fingers: :smile:
> Auto close issues that does not follow the issue templates

- proxy/nginx.conf
This example should help people doing what #1737 suggests
> Added simple example to nginx for further services

- docs/config-options.md
- transmission/start.sh
> Rename flood ui config option

- .github/workflows/issue_invalid_action.yml
I extended the previously mentioned action and added some more support for checkboxes and code boxes..tried it successfully on one of my repos 
https://github.com/pkishino/dive-dimmer
fixes #1754
> Created workflow for auto-close issues

- docs/rss-plugin.md
- plugins/rss/start.sh
- plugins/rss/transmission-rss.tmpl
This fork will fix the issue #781
> RSS plugin not supporting HTTP authorization

- Dockerfile
```txt
None
```
```txt
Add missing dependency for nslookup that presumably got lost in the switch from alpine to ubuntu.
```
- This PR fixes or closes issue: ```fixes #1796```
> Add nslookup

- scripts/selfheal.sh
```txt
None
```
```txt
Tidy up selfheal with a few aims:
- Be less verbose, only displaying useful log messages, basically if the status changes. (Feature)
- More closely mimic how the regular HEALTHCHECK behaves, namely during the starting phase. (Bugfix)
```
- None
- None
> Make selfheal less verbose

- docs/config-options.md
- openvpn/start.sh
Adds a script check for /scripts/openvpn-post-config.sh, designed so you can make any custom changes to the selected openvpn config file after everything else is ready.
```txt
```
```txt
This adds an option to make custom edits to openvpn files after everything else runs.
Special mention for issue #1797 since it allows an option to add custom DNS entries to fix a PIA bug that causes issues if you use a 10/8 internal network.
```
- This PR is related to issue: ```relates to #1797 ```
> Add openvpn-post-config.sh, ran after we finish any configuration tweaks (Passing the path to the selected ovpn file).

- openvpn/modify-openvpn-config.sh
```txt
```
```txt
keepalive option doesn't work together with the ping options which we're adding later.
If it is present in the configuration files provided by a VPN provider a user will see an error like this:
> Options error: --keepalive conflicts with --ping, --ping-exit, or --ping-restart. If you use --keepalive, you don't need any of the other --ping directives.
This patch automatically removes the keepalive option.
```
- This PR fixes https://github.com/haugene/docker-transmission-openvpn/issues/918
> Remove keepalive option from configuration files

- transmission/start.sh
```txt
<placeholder>
```
```txt
Replace the `route` command with `ip route` in transmission/start.sh
```
- This PR fixes or closes issue: ```fixes #1836 ```
> Replaced "route" command with "ip route".

- openvpn/privatevpn/update-port.sh
The PrivateVPN API for looking up the opened forwarded port has changed.
I tried forking the dev branch, but this file didn't exist there. It's my first fork, sorry if I made it the wrong way...
```txt
Changing the URL to the PrivateVPN open port lookup API.
At the moment the script is unable to lookup the opened port. 
This change was necessary to fix the access to the new API URL.
```
- There doesn't seem to be any opened issues claiming problems with the current script, but it is easy to miss that the script is failing if you don't check the logs. The docker container works without a problem even if this script fails, as it is not critical. Additionally, the old API was working until recently, so users might not have noticed the change yet. 
If user exposed functionality or …
> New API for open port lookup

- transmission/stop.sh
```txt
```
```txt
Fix TRANSMISSION_TIMEOUT_SEC
```
Bug due to incorrect var name.
> fix TRANSMISSION_TIMEOUT_SEC

- Dockerfile
- docs/config-options.md
- transmission/start.sh
```txt
```
```txt
Added support for Shift UI 
as per #1920 
```
- This PR fixes or closes issue: ```fixes #1835 ```
- This PR is related to issue: ```relates to #1920 ```
- Link to documentation updated (if done separately): ```included```
> Added support for Shift UI

- .github/ISSUE_TEMPLATE/bug_report.yaml
- openvpn/persistEnvironment.py
- openvpn/tunnelUp.sh
- privoxy/scripts/start.sh
- privoxy/scripts/stop.sh
```txt
none
```
```txt
openvpn tunnelUp was missing required env variables: fixed
privoxy start/stop same: fixed
PEER_DNS and PEER_DNS_PIN_ROUTES added to persistEnv file
```
> Fixed missing env variables

- .github/ISSUE_TEMPLATE/bug_report.yaml
- openvpn/modify-openvpn-config.sh
- openvpn/persistEnvironment.py
- openvpn/tunnelUp.sh
- privoxy/scripts/start.sh
- privoxy/scripts/stop.sh
```txt
<placeholder>
```
```txt
<placeholder>
```
> Updated master from dev 

- docs/run-container.md
`form` to `from`
```txt
<placeholder>
```
```txt
<placeholder>
```
> Fixed typo

- docs/faq.md
I think this is fine to go to master..but can retarget to dev if desired
```txt
<placeholder>
```
```txt
<placeholder>
```
> Fix minor typos

- docs/faq.md
- docs/provider-specific.md
```txt
None
```
```txt
Add documentation on how to configure for Njal.la (https://njal.la/vpn/) VPN.
I also added an example command on how to use `docker exec` to verify container is connected to VPN.
```
Just doc update. None of the boxes above applies.
If user exposed functionality or configuration variables are added/changed: None
> Add some documentation on njal.la configuration

- openvpn/utils.sh
```txt
```
```txt
Fix when DEBUG  is not set.
```
- This PR is related to issue: ```relates to #2096```
> Fix for #2096 when not value is set for DEBUG

- docs/config-options.md
- docs/faq.md
- openvpn/start.sh
- openvpn/tunnelDown.sh
- transmission/start.sh
```txt
```
```txt
To allow custom scripts to be ran after the container connects to the VPN, for example to fetch your VPN IP address
```
N/A
> Add ability to run custom script after routes are added

- docs/provider-specific.md
- openvpn/nordvpn/configure-openvpn.sh
fix doc typo + fix curl output filename
```txt
None
```
```txt
* Fix typo in documentation.
* Fix output filename in curl command.
```
- This PR is related to issue: ```relates to #2104```
> Fix NORDVPN download (appeared in PR#2104)

- docs/building-blocks.md
> Fix building-blocks docs links

- .gitignore
- docs/config-options.md
- openvpn/start.sh
```txt
<placeholder>
```
```txt
use docker secrets to define openvpn_username and openvpn_password. so credentials are not anymore in docker-compose file, no in docker environment.
if secrets are not found, previous way to define vars are still valid.
Please note that TRANSMISSION credentials are not concerned in the PR.
```
> use docker secrets for openvpn credentials

- .github/PULL_REQUEST_TEMPLATE.md
- docs/building-blocks.md
- docs/config-options.md
- docs/debug.md
- docs/faq.md
- docs/tips-tricks.md
```txt
<placeholder>
```
```txt
<placeholder>
```
> Fix minor typo in docs

- transmission/updateSettings.py
None
Checks for the existing settings file as normal but catches the JSON decode error when attempting to read a malformed
settings file, such as an empty file or a file that can't be parsed by the JSON parser. When this error is caught, the default settings are then used, and later written to the updated `settings.json` file as per normal.
- Fixes #1484
> Gracefully handle malformed existing settings.json file on startup

- docs/config-options.md
```txt
None
```
```txt
change information in doc as code evolved, regarding docker secrets.
```
> openvpn secrets: fix doc

- docs/web-proxy.md
- privoxy/scripts/start.sh
```txt
None
```
```txt
Privoxy listen to all address including the tun interface, exposing the proxy to internet.
this PR is to change privoxy config to listen only to eth0 interface, not all interface.
At the moment, this is not a switchable feature. 
in file /etc/privoxy/config
line `listen-address 0.0.0.0:8888`will become `listen-address 172.x.y.z:8888`
```
- This PR fixes or closes issue: ```fixes #2194```
> proxy: listen only to eth0 address.

- docs/config-options.md
N/A
Update link to list of config options. The current link is dead and only directs to the transmission repo.
- ~~[ ] The code change is tested and works locally.~~
- ~~[ ] There is no commented out code in this PR.~~
> Update config option link

- docs/tips-tricks.md
Add "Let other containers use VPN" Section
Add real example
Add Test instructions
Kind of solution for #1558
```txt
<placeholder>
```
```txt
Add "Let other containers use VPN" Section
Add real example
Add Test instructions
Kind of solution for https://github.com/haugene/docker-transmission-openvpn/issues/1558
```
- This PR fixes or closes issue: ```fixes #1558```
- This PR is related to issue: ```relates to #1558```
> Add "Let other containers use VPN" Section

- openvpn/custom/config-failure.sh
- openvpn/modify-openvpn-config.sh
- openvpn/persistEnvironment.py
- openvpn/start.sh
- openvpn/tunnelUp.sh
```txt
None
```
```txt
When a config fails it would be nice if a script could be ran to check things are okay before it runs again.
For example check for updates to the config itself, or for updates to credentials.
There isn't enough time before container restart on failure so how this works in reality is the script will run
the next time the config is used.
This is a little bit like `openvpn-post-config.sh`, but only runs if the config has previously failed to connect.
```
- Add variable `CONFIG_MOD_FAILURE_SCRIPT`
- Allows configs to have a `config-failure.sh`
> Execute a script on VPN connection failure

- docs/supported-providers.md
```txt
<placeholder>
```
```txt
<placeholder>
```
> Added provider

- docs/provider-specific.md
```txt
<placeholder>
```
```txt
<placeholder>
```
> IPv6 needed for OVPN

- openvpn/start.sh
```txt
<placeholder>
```
```txt
Replacing `ip route add` with `ip route replace` would avoid raising an `RTNETLINK answers: File exists` error in case the route already exists
```
> Replace `ip route add` with `ip route replace`

- openvpn/ovpn/configure-openvpn.sh
Apologies for my foolishness with Github.  I'm not well versed in it.  I rebased mine to dev instead of master and then am doing a new PR that should have just the single file.  Ref:  #2298
> Fixing my commit error - #2298

- docs/config-options.md
- docs/faq.md
- openvpn/start.sh
```txt
```
```txt
Issue #534 Adding secret support for rpc credentials as well.
```
- This PR fixes or closes issue: ```closes #534 ```
> Added docker secret support for rpc credentials

- docs/vpn-networking.md
```txt
<none>
```
```txt
add a --name tag to the docker run commmand (already done it for you, feel free to change te name tho)
```
- This PR is related to issue: ```relates to #1558``` 
- Link to documentation updated (if done separately): ```https://...``` This is the docs
> --nametag to the vpn networking docs

- openvpn/start.sh
```txt
```
```txt
Delete tun device if exists when create_tun_device is set
```
- This PR fixes or closes issue: ```fixes #2296```
> Delete tun device if exists when create_tun_device is set

- docs/provider-specific.md
Pasting again. Not sure what I did this morning!
```txt
<placeholder>
```
```txt
<placeholder>
```
> Ovpn trying again

- docs/provider-specific.md
Missing ' and a VAR mistyped.  Fixed.
```txt
<placeholder>
```
```txt
<placeholder>
```
> Two typos fix

- Dockerfile
bump ubuntu image to upgrade to openvpn 2.5.5
You can see openvpn 2.5 changes here: #1511 
```txt
<placeholder>
```
> Bump to ubuntu 22.04 to upgrade openvpn

- .circleci/config.yml
- .github/workflows/docker-image-builds.yml
- .github/workflows/image-build-template-workflow.yml
- .github/workflows/image-build.yml
- Dockerfile
- README.md
```txt
No change to the code within the images
```
```txt
Move our image builds from CircleCI to GitHub Actions.
This because we're using multiple features in the GitHub ecosystem already and it's nice to add this as well.
But also because CircleCI has a 1 hour timeout for free projects and that didn't cut it to build the
Transmission-4.0.0-beta release with cmake and make commands taking a long time (in 3 parallel builds)
```
- This PR is related to issue: #2357
> Move image builds to GitHub Actions

- docs/supported-providers.md
- openvpn/start.sh
```txt
No
```
```txt
Do not run modify-openvpn-config.sh on mounted VPN config(s).
```
- This PR fixes or closes issue: fixes #2274
> Fix sed busy

- Dockerfile
```txt
Ubuntu 22.04 changed to NFTables from IPTables and defaults to using iptables-nft for calls to iptables. This fix changes it to use iptables-legacy which allows unchanged iptables commands to be supported until they can be updated.
```
- This PR fixes or closes issue: fixes #2455
- This PR is related to issue: relates to #2455
> Fix to use iptables-legacy rather than iptables-nft

- openvpn/persistEnvironment.py
something environment like:
`name=foo bar` 
will be invalid in the environment file, in a real example, it will be like `provider= SE Sto`.
Simply add change it to `provider="SE Sto"` will fix that.
```txt
<placeholder>
```
```txt
<placeholder>
```
> Fix bug: the evironment file will be invalid

- scripts/healthcheck.sh
```txt
previous commit introduced an incorrect regex, there no side effect, except that the code is never executed.
thanks to @GrahamDennis who alerted me, here is a suggestion for change.
```
- This PR is related to ```PR #2494```  
Tests:
```
~$ [[ Y =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
OK
~$ [[ Yes =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
OK
~$ [[ YES =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
OK
~$ [[ True =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
OK
~$ [[ true =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
OK
~$ [[ false =~ [yY][eE]?[Ss]?|[tT][Rr][Uu][eE] ]] && echo OK
~$ [[ N =~ …
```
> fix regex for webproxy eth0 check

- README.md
- docs/index.md
```txt
```
```txt
docs
```
- This PR is related to issue: relates to #2485
> documentation: remove circleci shields

- openvpn/nordvpn/configure-openvpn.sh
```txt
```
```txt
Nordvpn custom script embeded in this project has some issue when dns and ping checks are ran and failure is not explicit.
This PR is a a rewrite of the custom script to fix silent failure.
Also were added more explicit tests analysis.
```
> review nordvpn error exit messages + tests

- docs/tips-tricks.md
```txt
None
```
```txt
Add an example socks5 proxy integration to the Tips & Tricks page.
```
- This PR addresses the discussion: https://github.com/haugene/docker-transmission-openvpn/discussions/2017#discussioncomment-5162864
> Socks5 example doc

- docs/tips-tricks.md
```txt
<placeholder>
```
```txt
<placeholder>
```
> Docs: add capabilities for Podman to tips&tricks

- openvpn/persistEnvironment.py
```txt
```
```txt
Quote the variables generated by the python script so they don't break export calls
```
- This PR fixes or closes issue: fixes #2406 
> fix: Add quotes on generated variables to avoid braking with spaces

- .github/workflows/image-build-template-workflow.yml
- docs/tips-tricks.md
```txt
<placeholder>
```
```txt
<placeholder>
```
> prep new master

- Dockerfile
```txt
<placeholder>
```
```txt
Improves build process by building a .deb and using it for install, also reduces the image size.
```
> Added step to build a .deb file to install and reduce image size

- transmission/start.sh
N/A
On RaspberryPi / Debian, the PIA scripts are not executable.  
`5.0.2` resolved `configure-openvpn.sh` not getting executed by only checking that the file exists (b6c404900b5c79c747e79a71c6beaccedbca55dc), but `update-port.sh` is still checked for executability and is not run.
- This PR fixes or closes issue: ```fixes #2459```
> Check for update-port script existing instead of being executable

- Dockerfile
```txt
this should fix TWC not working with transmission 4.0
```
```txt
<placeholder>
```
- This PR fixes or closes issue:  #2587
> Fixed TWC paths

- .github/workflows/image-build-template-workflow.yml
```txt
```
```txt
add caching to build step. github has native caching for docker build action
```
> Add docker build cache to speed up build time

- transmission/userSetup.sh
```txt
<placeholder>
```
```txt
<placeholder>
```
- This PR fixes or closes issue: fixes #2585 
> Strip double quotes from umask check

- Dockerfile
- openvpn/fetch-external-configs.sh
```txt
moves away from downloading a zip archive or full git clone of the vpn-configs-contrib repo
to a shallow clone of the repo in the /config folder to retain the downloads between container update/recreation.
this will shave off some startup time.
```
```txt
no more zip download or full clone
git clone with depth 1
move to /config for caching configs
```
- This PR fixes or closes issue: ```fixes #2591 ```
- This PR is related to issue: ```relates to #2591 ```
> move vpn config download to /config

- Dockerfile
```txt
None
```
```txt
Use most recent alpine docker image to create TransmissionUIs layer
```
- use most recent alpine image instead of an alpine version which is already End of support (https://www.alpinelinux.org/releases/)
> use alpine:latest for TransmissionUIs build stage

- docs/provider-specific.md
```txt
<placeholder>
```
```txt
NordVPN requires us to use server credentials instead of our regular login. Updated the docs to reflect that.
```
- This PR provides more information about using server credentials.
> Updated provider docs docs to include tip to use service credentials for NordVPN

- privoxy/scripts/start.sh
…ddress
```txt
```
```txt
Fixing #2692 I introduced in PR #2610 
```
- [ X ] Bugfix (non-breaking change which fixes an issue)
- This PR fixes or closes issue: ```fixes #2692 ```
- [ X ] The code change is tested and works locally.
- [ X ] There is no commented out code in this PR.
> Switched the order of events, to remove the ipv6 before sed-ing the address

- .github/workflows/check-transmission-releases.yml
* Fix incorrect order for parsing version from latest release on github
- This PR fixes or closes issue: ```fixes #2691```
- This PR is related to issue: ```relates to #2691 ```
> Fix transmission version check workflow

- .github/workflows/docker-image-builds.yml
```txt
<placeholder>
```
switch back to 1 builder for all platforms instead of multi runner builds, which was failing on previous pushes with only 1 architecture from PR #2694. this still consolidates the multi image builds into 1 workflow with matrices to set the context for each image build.
> Switch main Image build to combined platform builder

- openvpn/start.sh
Reverts haugene/docker-transmission-openvpn#2702
> Revert "Remove script_security"

- Dockerfile
- openvpn/fetch-external-configs.sh
```txt
Nothing should break. This change stops things from breaking.
```
```txt
line 67 in openvpn/fetch-external-configs.sh uses a "+" style concatenation technique to create the config_repo_old variable. This was throwing errors in my container logs. Changing the concatenation style to something more agreeable to bash resolves the issue.
```
> fixing invalid concatenation

- .github/workflows/check-transmission-releases.yml
- .github/workflows/docker-image-builds.yml
- .github/workflows/docker-transmission-builds.yml
- .github/workflows/mkdocs.yml
- Dockerfile
- README.md
- docs/tips-tricks.md
- openvpn/fetch-external-configs.sh
- upstream/Dockerfile
```txt
Add the installation of natpmpc to the container so that future update-port.sh scripts can use it to set-up port-forwarding. 
For example, ProtonVPN provides instructions for how to manually configure port-forwarding for Linux using natpmpc. See here: https://protonvpn.com/support/port-forwarding-manual-setup/#linux
An example, please see my branch of vpn-configs-contrib for an example of update-port.sh for ProtonVPN. 
https://github.com/muggajoe/vpn-configs-contrib/blob/dev/openvpn/protonvpn/update-port.sh
```
> Add natpmpc

- .github/workflows/check-transmission-releases.yml
```txt
set git user config
```
- This PR fixes or closes issue: ```fixes https://github.com/haugene/docker-transmission-openvpn/actions/runs/7132216212```
> fix: transmission version check

- .github/workflows/check-transmission-releases.yml
- Dockerfile
```txt
<placeholder>
```
```txt
<placeholder>
```
> Change transmission-web-control to actively maintained project

- docs/provider-specific.md
- This PR fixes or closes issue: #2803
> protonvpn.net.udp –> protonvpn.udp

- openvpn/nordvpn/configure-openvpn.sh
AES-256-CBC cipher is no longer working for NordVPN. Use AES-256-GCM instead.
```txt
```
```txt
NordVPN's servers do not work with AES-256-CBC cipher anymore. AES-256-GCM cipher can be used instead.
```
- This PR fixes or closes issue: ```fixes #2820```
> Use a supported cipher in nordvpn configuration

- .github/workflows/check-transmission-releases.yml
```txt
None
```
Part 2 of https://github.com/haugene/docker-transmission-openvpn/pull/2843, as `on schedule` can only be run on master branch.
> transmission version: part 2

- .github/workflows/mkdocs.yml
```txt
none
```
```txt
Only run mkdocs Action when there are changes to contents of docs directory.
```
> mkdocs: only run when there are changes to docs

- plugins/rss/Dockerfile
```txt
none
```
```txt
Fix RSS build, based on https://github.com/ffi/ffi/issues/1103
```
> Fix rss build

- docs/faq.md
```txt
The `http://ipmagnet.services.cbcdn.com/` link in docs is dead, so I think we should swap it for the working link, `https://github.com/cbdevnet/ipmagnet/`.
```
> Docs: Changes ipmagnet dead link for working one

- Dockerfile
Upgrade ubuntu base image to 24.04 LTS
```txt
No breaking change that I'd know of. Tested build and running only with linux/amd64 platform though.
```
```txt
Upgrade the ubuntu base image from 22.04 LTS to 24.04 LTS, and upgrade transmission to 4.0.6.
```
> feat(upgrade): ubuntu 24.04 LTS for base (was 22.04)

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/workflows/docker-image-builds.yml
- .github/workflows/docker-transmission-builds.yml
- .github/workflows/mkdocs.yml
- Dockerfile
- README.md
- docs/provider-specific.md
Maybe some light breakage. See more details in PR: [2941](https://github.com/haugene/docker-transmission-openvpn/pull/2941)
End goal: dev/master branches are up to date with each other and Transmission is installed from official repositories.
- This PR is related to issue: relates to #2939
> Merge master into dev
