haugene/docker-transmission-openvpn

Dockerfile, README.md, piaconfig/config.ovpn, transmission/down.sh, transmission/run.sh
Got rid of the base image. Running everything through service hooks in OpenVpn. Cleaner.
=> init method

transmission/start.sh
Fix for issue outlined in https://github.com/haugene/docker-transmission-openvpn/issues/36
Also slipped in a —logfile param so transmission will log to disk.
=> Fix entropy error, enable transmission logging

README.md, docker-compose.yml
I had some trouble getting nginx to reverse-proxy to transmission using my local IP address. The solution in the end was to add a link from the nginx container to the openvpn container. This causes docker-compose to map the name 'openvpn' to the IP address of the actual container at start up.
This would also allow you to include a portable nginx.conf file in the repository that didn't require the user to change anything. Let me know if you would like me to open a second pull request adding a copy of my nginx.conf that works with this.
=> Add a link from nginx to openvpn in docker-compose

README.md
=> Updated Readme with synology instructions

Dockerfile, README.md
Re: #69 
README changes explaining about systemd integration.
Plus Dockerfile change to install and use Yelp's dumb-init to avoid zombies.
I notice that there is a new version of dumb-init release since I started using it 12 days ago but I left the Dockerfile with v1.0.1, as that's the one I've been testing.
Cheers,
Dave
=> systemd integration

README.md, openvpn/start.sh
This PR adds support for e.g. -e LOCAL_NETWORK=10.0.0.0/24 so the container stays available on the local network and access doesn't require a proxy.
This duplicates #81 against dev branch.
=> Add support for local network route

Dockerfile, Dockerfile.armhf, README.md, transmission/environment-variables.tmpl, transmission/start.sh, transmission/userSetup.sh
By default transmission will still run as root so as to not break backwards compatibility.
This should address issue #89, though it doesn't do the auto detect the existing files thing that was suggested as a neat feature.
=> added support for uid/gid

Dockerfile
My setup uses wget to initiate sickrage postprocessing. Its only a minor change but nice for those (if any) that also use this so we dont need to fork.
=> Added wget

transmission/updatePort.sh
Hi, 
After experiencing port issues in #167, I tracked down what might be causing them. In my experience, the curl request to PIA would timeout, and the `updatePort.sh` script wouldn't handle that error properly, and proceed to set an empty port to transmission which resolved to port 0.
I added some additional error checks to make sure we've got a port from PIA before setting it, as well as fail if curl receives an HTTP error. I also made the curl downloading output silent, as it was cluttering up logs.
Hope this helps, please let me know if I should make any changes!
=> Added more robust error handling around checking for new port from PIA

docker-compose-armhf.yml
- Removed double quotes from the "OPENVPN_OPTS=" line due to literal interpretation that would cause an issue at /openvpn/start.sh:57 when executed.
- Fixed failing "proxy/build" instruction. Splitting into "context" and "dockerfile" subkeys prevents the error "TypeError: You must specify a directory to build in path"
- [Proposal] Introduced "image: haugene/rpi-transmission-openvpn*" lines to each docker-compose structure to transition to Docker Hub hosted images in the future. (see https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/)
=> Fix docker-compose errors and introduce image names

README.md, docker-compose-armhf.yml, docker-compose.yml
Thought it'd be nice for various security reasons to reduce how many privileges this container has. Running with only the necessary privileges also makes it possible to use user namespaces (you need `--userns="host"` if you're using `--privileged`).
=> Reduce the amount of privileges needed

docker-compose.yml
Would be great if this could be tested on a couple other platforms. This change is required for docker on Windows 10. 
Addresses #236
=> docker-compose.yml: remove quotes

transmission/start.sh
During testing with PureVPN, there are some situations where the up script is executed when a VPN tunnel is not actually established.  See log sample below.   This script update will kill the openvpn and have the tunnel re-established when this occurs rather then starting transmission with no VPN tunnel established
```
Thu Nov 30 14:55:38 2017 TUN/TAP device tun0 opened
Thu Nov 30 14:55:38 2017 /etc/transmission/start.sh tun0 1500 1558   init
Up script executed with tun0 1500 1558   init
ERROR, unable to obtain tunnel address
```
=> restart openvpn if the up script is executed and no ipv4 is bound 

openvpn/start.sh
Instead of bailing when the OpenVPN user and password aren't defined in the environment, we should instead check and see if we already have an existing /config/openvpn-credentials.txt file from a persistent volume that can be used first.
This is important because --link will share environment variables with other containers, and it would be preferable to not need to include external auth information with that.
=> Allow a pre-existing /config/openvpn-credentials.txt file.

transmission/start.sh
=> set /bin/bash as shell for user when starting transmission

README.md, transmission/environment-variables.tmpl, transmission/start.sh
I discovered that with some VPN providers (e.g. Mullvad) the routes have a potential issue.
This addresses this issue by allowing the user to drop the default route after OpenVPN has connected, but before Transmission is started.
Before:
```
root@62a71b505acd:/# ip r
0.0.0.0/1 via 10.8.0.1 dev tun0
default via 172.19.0.1 dev eth0
10.0.0.0/8 via 172.19.0.1 dev eth0
10.8.0.0/16 dev tun0  proto kernel  scope link  src 10.8.0.6
82.103.140.213 via 172.19.0.1 dev eth0
128.0.0.0/1 via 10.8.0.1 dev tun0
172.19.0.0/16 dev eth0  proto kernel  scope link  src 172.19.0.4
```
After (with `DROP_DEFAULT_ROUTE`=`true`:
```
root@e9150d61d626:/# ip r
0.0.0.0/1 via 10.8.0.1 dev tun0
10.0.0.0/8 via 172.19.0.1 dev eth0
10.8.0.0/16 dev tun0  proto kernel  scope link  src 10.8.0.8
128.0.0.0/1 via 10.8.0.1 dev …
```
=> add option to drop the default route on providers, that do not override it properly

Dockerfile.alpine
The "bash" environment was absent from the Alpine image, making "dumb-init" unable to start the main script "start.sh"
Also, kettu was not installed in the proper directory
=> Add missing bash dependency in Alpine image

proxy/Dockerfile.armhf
Use the same resin/rpi-raspbian:stretch image for proxy to not have to download another image and save space.
=> Use same rpi-raspbian:stretch image for proxy

README.md, openvpn/start.sh
This PR is for issue #366 
it adds support for multiple servers in OPENVPN_CONFIG
If a list of files is provided in OPENVPN_CONFIG, a file in the list is chosen randomly
=> Add support for multiple servers in OPENVPN_CONFIG

transmission/start.sh, transmission/userSetup.sh
By default in Synology NAS the user Root creates files with the permissions "---------" (0).
Other users can't access to file after change file owner.
I add `chmod 640` after file creates and before `chown `command if attributes = 0.
```
echo "Check transmission settings.json file attributes"
SETTINGS_PATH=${TRANSMISSION_HOME}/settings.json
SETTINGS_ATTRIBUTES=$(stat -c %a ${SETTINGS_PATH})
if [ ${SETTINGS_ATTRIBUTES} = 0 ]; then
chmod 640 ${SETTINGS_PATH} && echo "INFO: Attributes of setting.json changed to 640"
fi
```
P.S. This is my first pull request.
Fix #423
=> Fix settings.json file attributes on Synology NAS.

openvpn/start.sh
Simple fix to remove leading and trailing whitespace in the OPENVPN_CONFIG. This allows for
```
"OPENVPN_CONFIG= site a,site b , site c ,        site d"
```
and any variation there-of.
=> Fix for leading or trailing space in OPENVPN_CONFIG.

plugins/rss/Dockerfile.armhf
Currently the dockerfile of arm didn't work because:
* Ruby max version for jessie is 2.1
* This image needed to install the libc6-dev package
* There was a typo
All of them are fixed now
=> Fix transmission-rss dockerfile for arm

transmission/start.sh, transmission/stop.sh
The *start.sh* and *stop.sh* scripts receive a set of arguments from *openvpn* when invoked from *tunnelUp.sh* and *tunnelDown.sh*. They are:
* `$1`: network interface for the VPN (e.g. `tun0`)
* `$2`: interface MTU (e.g. `1500`)
* `$3`: link MTU (e.g. `1570`)
* `$4`: local IP (e.g. `10.47.10.6`)
* `$5`: remote IP if TUN (e.g. `10.47.10.5`), network mask if TAP
* `$6`: "init" or "restart"
This commit makes these arguments available in *transmission-pre-start.sh*, *transmission-post-start.sh*, *transmission-pre-stop.sh* and *transmission-post-stop.sh* for those users who might need them.
=> Pass on arguments to pre and post start/stop hooks

openvpn/nordvpn/default.ovpn
In commit 17768dca5b85eb922184025fa935677f602d5539, the file that the default conf that Nord VPN was pointing to was removed, so the container will no longer start (errors out saying it can't find the file):
```
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default
```
**Note:** I don't know if it matters what the default was... I just picked `nl180.nordvpn.com.tcp.ovpn` at random, you can change it if it really matter.
What's weird, is even if I override the config it should use with `OPENVPN_CONFIG`, it still tries to access this file and won't start. For now, I'm sticking to `2.0` to be able to get it to work.
=> Fix broken Nord VPN

Dockerfile.armhf, plugins/rss/Dockerfile.armhf, proxy/Dockerfile.armhf
[Building ARM containers on any x86 machine, even DockerHub](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/)
=> Add ability to automatically generate ARM images on DockerHub

transmission/start.sh, transmission/stop.sh
When using `"$*"` all arguments ended up as `$1` in the hook scripts, i.e. `$2` and forward they were all blank. This fixes the code so it works as originally intended (see #547).
=> Fix arg passing to start/stop script hooks

README.md
I've added a chmod to tun device to allow unprivileged docker containers to use tun device and send traffic through the vpn.
Related to this issue: https://github.com/haugene/docker-transmission-openvpn/issues/41
=> Fix unpriviligied user to use tun device under docker

Dockerfile.alpine
transmission-cli package contains transmission-remote which is called by /etc/openvpn/updatePort.sh
fixes #647
=> Add transmission-cli package

README.md, openvpn/start.sh
I run this image on Kubernetes and I would like to create a tun device inside the container on startup, like this:
```bash
#!/bin/bash
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 600 /dev/net/tun
```
Now I override the command of the container but it would be nice if this can be handled as the transmission scripts, like this:
```yaml
command: ["/bin/bash"]
args: ["-c", "/scripts/openvpn-pre-start.sh && dumb-init /etc/openvpn/start.sh"]  
```
I only added the pre-start because that one seems the most relevant to me but I can add the post-start, pre-stop etc. if necessary.
=> Adds pre-start for openvpn

Dockerfile.armhf
Fixes #705 and #721 
The image just seem to have moved namespaces so just a rename. I am not able to test this image @chilicheech might?
=> Replace resin with balenalib since the armhf image has been moved

README.md, openvpn/start.sh
As stated in #697 an option to enable creation of the /dev/net/tun device inside the container. This should mitigate the need to pass the device from the host to the container.
I create the device as the Linux kernel documentation states [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/tuntap.txt?id=HEAD#n36).
This also enables the container to be used on Kubernetes, the `--device` parameter isn't available (only block and character devices).
I purposefully haven't written that much documentation because I don't know how to proceed. If this works like it should on NAS devices then most of that documentation can be deleted. If this totally mitigates the purpose of attaching a device the whole readme needs cleaning up.
In short please …
=> Create new CREATE_TUN_DEVICE variable

Dockerfile, README.md, scripts/healthcheck.sh
Sometimes transmission is unable to connect to the internet because the VPN connection shut down. The container then just sits there not doing anything, without it being noticed. A simple container restart fixes this of course, but the main problem is it going unnoticed.
Therefore I added a docker health check. It simply pings to see if the network is still up. I made a script instead of directly calling ping, because the ping command uses exit code 2 in some circumstances, which you shouldn't do according to Docker documentation. The script simply catches the ping exit code and returns either 1 or 0, to make the exit code up to spec with docker guidelines.
This also makes it easier to change or extend the way the health check is done, if need be.
The default host is google.com, this can …
=> Added a health check

openvpn/privatevpn/default.ovpn, openvpn/privatevpn/london-uk.ovpn, openvpn/privatevpn/los-angeles-usa.ovpn, openvpn/privatevpn/stockholm-sweden.ovpn
The PrivateVPN servers changed host names from .privatevpn.com to .pvdata.host, see https://privatevpn.com/serverlist/ .
[ Please use squash commit when merging this pull request (I edited these config files online on github.com directly, so had to commit them individually). ]
=> PrivateVPN server domain name change (October 2019)

docs/dockerenv.md
Tiny change, just updating documentation with a link to the example [DockerEnv](https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv) file in the repo.
=> Link to the DockerEnv file

openvpn/nordvpn/updateConfigs.sh
I do not provide the `NORDVPN_PROTOCOL` variable in my container.
`NORDVPN_PROTOCOL` is defaulted to `"udp"` in `/openvpn/start.sh`
[L96 here](https://github.com/haugene/docker-transmission-openvpn/blob/dev/openvpn/nordvpn/updateConfigs.sh#L96) checks and provides the final portion of the .ovpn download URL which includes `.udp1194` (or `.tcp443` if `NORDVPN_PROTOCOL` was set to "tcp")
The end result in these checks and definitions causes the download URL to include an extra `.udp` in the address.
In my logs, this is the url it provides to `curl` from which is invalid:
`https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/us4436.nordvpn.com.udp.udp1194.ovpn`
It should end up being this instead:
`https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/us4436.nordvpn.com.u …
=> [NORDVPN] Fix setting download URL

openvpn/nordvpn/updateConfigs.sh
Fixing the NordVPN CND changes. Should fix downloading from wrong URL and getting a error like.
`Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.7)`
=> Fix for NordVPN as UDP and TCP CDN changed

openvpn/nordvpn/updateConfigs.sh
Downloading without any NORDVPN_ environment settings or with NORDVPN_ settings should result in correctly downloading:
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr380.nordvpn.com.udp.ovpn
and https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/nl542.nordvpn.com.udp.ovp as default (in this case with default UDP mode).
=> Fix for NORDVPN default and specific vpn config download

openvpn/elastictunnel/canada_toronto.ovpn, openvpn/elastictunnel/germany_frankfurt.ovpn, openvpn/elastictunnel/netherlands.ovpn, openvpn/elastictunnel/uk_london.ovpn, openvpn/elastictunnel/ukraine.ovpn, openvpn/elastictunnel/usa_ny.ovpn, openvpn/elastictunnel/usa_sf.ovpn
This PR adds support for [ElasticTunnel VPN Provider](https://elastictunnel.com/).
Supported regions:
- Canada, Toronto. OPENVPN_CONFIG value - `canada_toronto`
- Germany, Frankfurt. OPENVPN_CONFIG value - `germany_frankfurt`
- Netherlands. OPENVPN_CONFIG value - `netherlands`
- UK, London. OPENVPN_CONFIG value - `uk_london`
- Ukraine. OPENVPN_CONFIG value - `ukraine`
- USA, NY. OPENVPN_CONFIG value - `usa_ny`
- USA, SF. OPENVPN_CONFIG value - `usa_sf`
docker run argument values example:
```
docker run --cap-add=NET_ADMIN -d \
...
-e OPENVPN_PROVIDER=ELASTICTUNNEL \
-e OPENVPN_CONFIG=canada_toronto \
...
```
=> Add support for ElasticTunnel VPN provider

transmission/userSetup.sh
In a multi-user setup group write permissions are nice to have.
=> Add group write permission to watch folder.

Dockerfile
Related to https://github.com/haugene/docker-transmission-openvpn/pull/939#issuecomment-574247813.
The official OpenVPN sources do not work for some reason, therefore the Ubuntu repositories are taken. Current version there as of this PR is 2.4.4.
=> Fix build errors with the base Dockerfile

Dockerfile.armhf, openvpn/start.sh
The way transmission is packaged in stretch leads to memory issues:
- https://github.com/transmission/transmission/issues/313#issuecomment-446005020
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865624
The way this manifests for me is that my raspberry pi keeps running out of memory and becomes unresponsive.
The was fixed in buster/transmission-2.94
I've built and pushed this to [my dockerhub repo](https://hub.docker.com/r/fixl/transmission-openvpn/tags) for testing.
=> Fix 2.92 memory issue in armhf image

README.md
`docker-compose` is standard, and following `linuxserver`'s excellent example, including it in the `README.md` enables a far more efficient quick start from Docker Hub.
=> Add docker compose example to README.md

Dockerfile.alpine, Dockerfile.armhf
Add `HEALTHCECK`s to armhf and alpine images as well.
This seems like this never made it from [this commit](https://github.com/haugene/docker-transmission-openvpn/commit/0abe1912f4bd41c25ad5b28e04f671b5c6f9238a) to the other two images.
This is similar to #1009
=> Add health check to armhf and alpine image

transmission/start.sh, transmission/userSetup.sh
```
Sun Apr  5 20:54:10 2020 Initialization Sequence Completed
Couldn't (re)open log file "/dev/stdout": Permission denied
```
```
Transmission startup script complete.
Sun Apr  5 20:56:18 2020 Initialization Sequence Completed
[2020-04-05 20:56:19.725] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2020-04-05 20:56:19.725] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
```
The `DOCKER_LOG` parameter wasn't working with a `PUID`/`GUID` since `/proc/1/fd/1` is owned by root:root.
I tried chowning that path but it wouldn't persist since it isn't designed for that. `/dev/stdout` is the userspace equivalent and is chownable :)
Couldn't resist and fixed the indenting in the file. Sorry for the noise, for just the fix check 8b70873
=> Fix logging to stdout when using a RUN_AS user

openvpn/start.sh
VPNBOOK password is provided as a picture/image. The http://api.ocr.space/parse/image service erroneously sees a space between certain character combinations. Since passwords generally do not contain spaces, this extra awk expression removes the space.
=> Removed space within parsed VPNBOOK password.

transmission/start.sh, transmission/updatePrivateVPNPort.sh
Had to MITM attack the Mac PrivateVPN client to sniff out the mechanism it uses to fetch the forwarded port you are assigned on connection. Despite this, the implementation was straight forward as it's just an unauthenticated fetch to their API with your local tunnel IP in the query string.
I built the image locally and span it up with `OPENVPN_PROVIDER=PRIVATEVPN` and `OPENVPN_CONFIG=SE Stockholm` and it configured the port correctly:
```
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1001
User gid:    1001
-------------------------------------
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Thu May 21 22:31:54 2020 /sbin/ip route add 193.180.119.2/32 via 172.17.0.1 …
```
=> Add automated forwarded port configuration for PrivateVPN

scripts/healthcheck.sh
container will be marked unhealthy when openvpn or transmission process is not running.
it will be up to the user to handle what to do then, (recommend autoheal)
fix #1189
=> Updated healthcheck to include openvpn and transmission process

openvpn/ovpn/Germany.ovpn, openvpn/ovpn/Sweden.ovpn, openvpn/ovpn/US.ovpn, transmission/userSetup.sh
OVPN seems to have changed their hostnames, as such,  I've updated the configs to use the new hostnames.
As a bonus, I fixed a logic error in UserSetup that caused an bash error if $PUID was set, but $PGID wasn't.
Fixes #1266
Fixes #1267
=> Update OVPN configs (plus a small bonus bugfix)

Dockerfile.armhf
Issue at https://github.com/haugene/docker-transmission-openvpn/issues/1283 . Unrar and similar packages are not included in armhf release, thus this package allows us to handle automatic extraction and similar. #1283
=> Adding p7zip and p7zip-full for unzipping on ARM archs

Dockerfile.alpine
Installing ufw from the community repository worked, but we should probably call it community and not testing.
=> Naming community repo as community

README.md
Figured it would be nice to have something front and center of the README if people start having issues with the `dev` images. Also to prepare people who are checking in on the project that there are changes coming, and possibly intrigue some people to join development or testing of the new features.
=> Update readme with info about upcoming release

openvpn/freevpn/configure-openvpn.sh, openvpn/modify-openvpn-config.sh, openvpn/nordvpn/configure-openvpn.sh, openvpn/nordvpn/updateConfigs.sh, openvpn/start.sh, openvpn/vpnbook/configure-openvpn.sh
This PR restructures the start.sh script a bit. Separating the provider specific scripts from the main script and making it more "pluggable" for new provider specific logic.
Main feature is to accept a URL for config files. This is an alternative to the "manual provider" way of using your own config without coding. Hopefully this will make life easier for those that find it a bit confusing with the volume mounts.
I will update the documentation and enhance this feature a bit more as it will also be an alternative to the frequent provider config updates if more people use it.
=> Adding support for fetching configs from URL

.circleci/config.yml
While investigating what seemed like a memory leak in the ARM64 docker image, I realized that the ARM64 docker image still uses Debian Stretch as its base image (limiting it to Transmission 2.92).  This PR corrects that by adjusting the CircleCI build instructions to build against Debian Buster
=> Update ARM64 image to use Buster as its base image

transmission/updateSettings.py
@haugene 
This addresses a bug introduced by moving from the old settings templating mechanism to using updateSettings.py. 
Previously the settings template controlled the output type when env var values were written to settings.json by having some values quoted and not others. After the move to updateSettings.py that control was lost and all were written as strings. Subsequently Transmission would pick those up and reset them when there's a type mismatch. E.g. a string given instead of an int for max peers "100" would get reset to 0. No torrents would actually download after that. With this change we look at the baseline settings for the expected setting type and coerce the value of the corresponding env var to that type. Tested by building locally and running.
=> Coerce env var values to expected types by settings.json

Dockerfile
If UFW is enabled and no RPC port is provided, the firewall blocks access to the web interface
fixes #1428
fixes #1431
=> Adds default env TRANSMISSION_RPC_PORT=9091

openvpn/pia/update-port.sh
Every time after completion of the initialization sequence, I found the `update-port.sh` script reports errors.
```
STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.
Fri Nov  6 15:10:53 2020 WARNING: OpenVPN was configured to add an IPv6 route ov
er tun0. However, no IPv6 has been configured for this interface, therefore the 
route installation may fail or may not work as expected.
Fri Nov  6 15:10:53 2020 Initialization Sequence Completed
yes: Broken pipe
curl: (3) URL using bad/illegal format or missing URL
Fri Nov  6 15:10:58 PST 2020: getSignature error
the has been a fatal_error
date: invalid date ''
port is 
curl: (3) URL …
```
=> Fix getSignature error

transmission/updateSettings.py
This PR prevents the logging of the rpc-password, which is a sensitive information, to the stdout.
Before:
```
Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
...
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to SuperSecretPassword1
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9092
...
````
After:
```
Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
...
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port …
```
=> Prevent logging rpc-password to stdout

docs/systemd-integration.md
CREATE_TUN_DEVICE is now set to true by default and spaces in OPENVPN_CONFIG are no longer escaped.
=> Changes to make systemd docs work with 3.0

docs/arguments.md
I was using the bind mount method for /etc/localtime as read only and was wondering if there was support for an environment variable instead. A few closed issues showed it is already there, but nothing on the documentation page for arguments mentions it.
=> Update documentation for timezone configuration option.

openvpn/persistEnvironment.py, transmission/start.sh
Setting the TZ environment variable is not respected by transmission log timestamps. It does show the correct time when running `date` interactively in the container, but logs still show UTC timestamps. Various issues have been opened for this and the answer has been to bindmount the host /etc/localtime to force it work. 
Since tzdata is already installed in the image, I hope this is a more elegant solution: copying the timezone data to the correct path before transmission starts. If possible, it'd be ideal to place this at the start of the container so any ufw, openvpn or other logs will also show the correct timestamp, but I was unable to trace where /etc/transmission/start.sh is called from /etc/openvpn/start.sh so this a start.
=> set timezone at startup

openvpn/pia/configure-openvpn.sh
It appears that PIA has changed their URLs from "openvpn{-strong/tcp/strong-tcp}-nextgen" to "openvpn{-strong/tcp/strong-tcp}". The old URLs no longer work properly.
See here: https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files
=> Update PIA configure-openvpn.sh with updated URLs

transmission/stop.sh
* Carry and improve #1514 
* Close #1513 
After testing in the container, I found out `ps -p` is not supported in alpine (with `busybox`). So we avoided a regression 😅 
I set the default timeout to 10 seconds, and set the timeout step to 1 second, which both prevent the "Waiting for ..." message if transmission shuts down under 1s, and reduce code verbosity.
=> Ensure transmission shutdown

openvpn/pia/update-port.sh
Closes #1532 
I'm pretty sure this line has no purpose (other than printing 3 new lines).
=> Remove cause of "yes: Broken pipe" error

scripts/healthcheck.sh
Fix #1582
For some reason, a 5 seconds timeout on ping specified as `-w 5` is sometimes too short for two pings to go through, most likely because of the delay between pings and...? I don't know, but it nevertheless causes some apparent ping loss, as the last ping is deemed unsuccessful. This in turn marks the container as unhealthy even when it is indeed connected to the VPN and able to reach the internet.
I just increased the timeout to 10 seconds (for 2 pings). This seems awfully long for 2 small pings, but 🤷
=> Increase healthcheck ping timeout

openvpn/tunnelDown.sh, openvpn/tunnelUp.sh
Add scripts to OpenVPN startup to update /etc/resolv.conf with VPN providers DNS servers, stopping DNS leakage. 
@clement-z already observed files to complete similar function are available in /etc/openvpn/. Visually they appear near identical (I haven't diff'd them), but both achieve the functionality desired.
This implementation uses:
/usr/share/openrc/support/openvpn/up.sh
/usr/share/openrc/support/openvpn/down.sh
However a valid alternative would be:
/etc/openvpn/up.sh
/etc/openvpn/down.sh
Only other point of note is setting DNS to correct values before transmission starts and after it closes.
Ref Issue #1455 
Prev pull req #1614 (cancelled because I can't manage my branches) (Sorry)
=> Fix DNS leak by updating /etc/resolve.conf

openvpn/start.sh, scripts/healthcheck.sh
See #1608 
The main idea is making DNS error clearly identifiable in the logs, and avoid [XY problem](https://xyproblem.info/)-type issues.
The commits add simple `nslookup` calls (using `HEALTH_CHECK_HOST` if set, or defaulting to `google.com`). If the lookup fails, then:
* In `openvpn/start.sh`, only a message is printed, as I guess it is possible to use only IPs for connecting to the VPN, and have DNS resolution set up after openvpn connects;
* In `scripts/healthcheck.sh`, if DNS resolution fails, the container is marked as unhealthy with the message "DNS resolution failed".
It might be worthwhile to also check resolution after connecting to the VPN, especially after #1614 is merged.
=> Add DNS resolution checks (fix #1608)

openvpn/start.sh
Related to #1615. @clement-z suggested something along these lines.
VYPRVPN sets $PWD to a deleted directory, which causes a cascade of
issues for the rest of `start.sh`.
This saves the current directory before sourcing `configure-openvpn.sh`
scripts, making sure such an issue cannot happen for any VPN.
A proper fix would be to avoid sourcing the script in the first place.
-----
I am unsure if I need to fix that issue at the source: https://github.com/haugene/docker-transmission-openvpn/blob/a4d65774f855a04070766e53346661f48c76fa0e/openvpn/vyprvpn/configure-openvpn.sh#L52
This technically isn't an issue *as long as long the script isn't sourced.* I preferred to solve it once and for all, but once again, changing `$PWD` is just one of many possible side-effect of sourcing that dir.
=> Make sure configure-openvpn.sh cannot change the current directory

transmission/start.sh
Follow-up to #1610 
Hard fail when `updateSettings.py` fails to set proper configuration. This prevents running transmission with incorrect configuration.
=> transmission: hard fail when settings cannot be converted

transmission/default-settings.json
Transmission default value for the ratio limit is `2.0`, not `2` (source: https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#scheduling). This slight difference causes the` updateSettings.py` script to treat this setting as `int` instead of `float`. 
Currently, passing float causes the following error:
```
Generating settings.json for Transmission from environment and defaults default-settings.json
Could not coerce TRANSMISSION_RATIO_LIMIT value 4.1 to expected type <class 'int'>
Traceback (most recent call last):
File "updateSettings.py", line 69, in <module>
env_value = setting_type(env_value)
ValueError: invalid literal for int() with base 10: '4.1'
```
After applying this patch everything works as expected:
```
Generating settings.json for Transmission from …
```
=> transmission: fix settings ratio limits to float values

openvpn/pia/configure-openvpn.sh
Fix #1619 
PIA download link was redirecting and setting a cookie, but those are
disabled by default unless `--cookie` or `--cookie-jar` are given. Since
the cookie was not set, the redirection was attempted again until we
reached the maximum redirection limit.
The `--cookie /dev/null` specifies an empty input cookie, which has the
effect to enable curl's handling of cookies.
=> Fix PIA infinite redirect on config download (see #1619)

.circleci/config.yml
PR for https://github.com/haugene/docker-transmission-openvpn/issues/1633
* create github personal access token with permissions for read/write packages as seen [here](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images)
* add the token as a Circle CI variable named GITHUB_PASS
* after first build has been published, package needs to be made public (defaults to private)
=> add ghcr publish

openvpn/tunnelDown.sh, openvpn/tunnelUp.sh
Reverts haugene/docker-transmission-openvpn#1621
this needs to be reworked as it will cause problems with no dns resolution before the tunnel is setup (cannot resolve vpn hostname )
=> Revert "Fix DNS leak by updating /etc/resolve.conf"

Dockerfile
git clone within a node container is sometimes broken in non-amd64
architecture systems. This commit fetches the Flood UI as a tarball from
GitHub instead of cloning.
=> Fix broken builds for non-amd64 platforms

docs/faq.md
Was running into me being dumb and not entering an actual subnet ID, wrote a quick FAQ entry and directions to get Network ID instead of the IP address of the gateway
toward #1558
=> Update faq.md to explain RTNETLINK error from invalid subnet mask/route

docs/faq.md
faq.md currently has both a static Table of Contents and a generated one on the right. This PR updates the static copy to include all the headers on the page currently, mirroring the dynamic one on the right (screenshot from before PR below)
https://i.imgur.com/mfmUbwu.png
=> Update static copy of Table of Contents on faq.md

Dockerfile
Followup of #1669 
Currently running this with #1691 on my cluster, feel free to try from ` lansible/transmission-openvpn:develop`
More info on `npm ci` here:
https://docs.npmjs.com/cli/v6/commands/npm-ci#description
Backticks in bash are the 'old style', new way is `$()` so updated that too :)
=> feat: update to alpine 3.13

openvpn/start.sh
As discussed in #1362 the route-up and route-pre-down options might be a better fit to start and stop Transmission with.
Some additional changes needs to be added to get the route-up script to work, but route-pre-down seems straight forward.
With this done. Will that automatically bring back support for the providers that run some `up /etc/openvpn/update-resolv-conf` action that has until now broken our start/stop mechanism? :thinking:
=> WIP: More correct start and stop scripts for Transmission

openvpn/fetch-external-configs.sh, openvpn/modify-openvpn-config.sh, openvpn/start.sh
As discussed in #1489 and that we have been planning for a while. We should move all the .ovpn config files to a separate repo to make a clearer distinction between config and code. That would reduce the amount of PRs and issues posted here and we could set up a codeowner-structure or otherwise engage more of the community to maintain configs.
Separating the configs like this also enables people to fork, edit and test new configs without getting their PRs merged. While many of our contributors are familiar with git, this would allow any user to fork the config repo and copy-paste a config from his/her provider and be up and running.
The PR is not done. But it might not be far from it. I'm wondering what you think about naming of the variables and what we'll call these "modes" of …
=> Moving configs to separate repo

openvpn/fetch-external-configs.sh
There are only very few providers's directories in https://github.com/haugene/docker-transmission-openvpn/tree/dev/openvpn and VPN_PROVIDER_HOME might very likely be missing for many providers without bundled setup scripts.
=> Don't fail `rm` if VPN_PROVIDER_HOME doesn't exist.

openvpn/modify-openvpn-config.sh
```txt
None
```
```txt
When "CONFIG_MOD_PING = 1" it can result in non-functional config files.
Especially when used in conjunction with "VPN_CONFIG_SOURCE = internal".
Namely because it doesn't ensure new options are being appended on a new line.
Also updated the remove code to ensure clean-up of "inactive" and avoid leaving lots of unnecessary empty lines.
```
- None
- None
=> CONFIG_MOD_PING breaks config files

scripts/route-pre-down.sh
See enhancement request #1362 
Try to gracefully stop transmission when stopping the container.
To enable: add `--route-pre-down /etc/scripts/route-pre-down.sh` to `OPENVPN_OPTS`
According to https://wiki.archlinux.org/index.php/transmission#Transmission_daemon_and_CLI
`pkill -3 transmission-daemon` or `transmission-remote --exit` is the proper way to stop the transmission-daemon, however, during my test `pkill -3` does not work. I was only able to get the exit log with `transmission-remote --exit`
=> Initial version of route-pre-down script

Dockerfile, transmission/userSetup.sh
Applies the `TRANSMISSION_UMASK` configuration to the download and incomplete directories. Solves the problem of hardcoded permissions in these directories.
The octal conversion requires changing the `userSetup.sh` script to be interpreted by `bash` instead of `sh`.
=> Apply Transmission umask setting to download directories

openvpn/start.sh
For the first few seconds after transmission and tinyproxy start, their traffic is not routed through the VPN. This is because we are calling openvpn with the option `--up /etc/openvpn/tunnelUp.sh`, and the `--up` script runs before ip routes are added. In other words, the VPN will be connected, but traffic will be routed outside of the VPN interface because openvpn has not changed the routing tables with the `ip route` command. In my testing, this seems to not cause an IP leak for transmission, because transmission takes a few seconds to load (however, depending on your setup, it could be a problem). I did find that tinyproxy can leak a few requests though, because tinyproxy starts up faster.
To fix this leak, I changed `--up` to `--route-up`, which runs after openvpn has modified the …
=> Fix IP leak for first few seconds after tunnel up

openvpn/tunnelUp.sh, transmission/start.sh
OpenVPN calls the `--up` script with arguments and environment variables, but it calls `--route-up` only with environment variables. Here, I switched the scripts to use the corresponding environment variables instead of arguments.
While I was testing this patch, I noticed another bug, related to #2020. The `updateSettings.py` script does not work for the legacy config location (`/data/transmission-home`), because we check for the legacy config folder and update `TRANSMISSION_HOME` after the python script has already run. I moved the `userSetup.sh` script before `updateSettings.py` to fix this.
- This PR fixes or closes: #2081
=>  Fix scripts to work with --route-up, and update settings.json in transmission-home folder 

openvpn/vyprvpn/configure-openvpn.sh
```txt
NA
```
```txt
rewrote this script to no longer call the cd command.
```
- This PR is related to issue:
- #1406
- #1615
- #1616
<details>
<summary>logs</summary>
```bash
22:50 # docker logs -f vpn_test
Creating TUN device /dev/net/tun
Using OpenVPN provider: VYPRVPN
Running with VPN_CONFIG_SOURCE auto
Provider VYPRVPN has a bundled setup script. Defaulting to internal config
Executing setup script for vyprvpn
Downloading OpenVPN configs into temporary file /tmp/tmp.wDWQRGY4eS
Temporarily extracting OpenVPN configs into directory /tmp/tmp.uXG03bPHk1
Removing /tmp/tmp.uXG03bPHk1 & …
```
=> removing cd command from vyprvpn download script

README.md, docs/run-container.md
```txt
None.
```
```txt
Update documentation of Docker run and compose templates to include /config volume
```
- This PR is related to issue: relates to -
https://github.com/haugene/docker-transmission-openvpn/discussions/1937#discussioncomment-4263241
https://github.com/haugene/docker-transmission-openvpn/pull/1974
https://github.com/haugene/docker-transmission-openvpn/pull/2020
=> documentation: add /config volume to templates

scripts/healthcheck.sh
**
```txt
<placeholder>
```
```
Running container internal address 172.18.X.X will change from time to time. This PR will check that privoxy's listening address is still correct. During healthcheck, privoxy's listening ip is compared to eht0 ip address.
container set with multiple listening address (eth0,eth1,eth2,eth3,...) is not in the scope of this PR.
fix #2489
```
- This PR fixes or closes issue: ```fixes #2489```
=> restart privoxy if docker changed eth0 address.

openvpn/start.sh
Reduce the complexity associated with creating RPC creds
```txt
<placeholder>
```
```txt
Simplify and fix RPC creds set up with docker secrets.
```
The current integration with docker secrets is flakey/overcomplicated.
For example in the case where there is an `rpc_creds` docker secret, which is the same as `transmission-credentials.txt` the environment variables won't be set to the correct credentials.
This pull requests, not only fixes that issue, but drastically reduces the complexity of the code.
If `rpc_creds` exists, its content will **always** be used as environment variables.
Environment variables are **always** written into the `transmission-credentials.txt` file.
=> Simplify RPC creds setup

transmission/userSetup.sh
```txt
<placeholder>
```
```txt
Fix bitwise decimal & octal
```
Also uses the TRASNMSISSION_UMASK variable instead of settings.json since updateSettings.py is called after userSetup.sh causing the TRANSMISSION_UMASK in settings.json to be stale when userSetup.sh accesses it.
- This PR fixes or closes issue: fixes #2450 
=> Fix bitwise decimal & octal

openvpn/fetch-external-configs.sh
```txt
```
```txt
Fix a crasher that obscures another problem. If curl to get configs fails, there is an error in cleaning up.
./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable
```
=> Fix crash in fetch-external-configs on unset vars

.dockerignore, .github/workflows/image-build-template-workflow.yml, docs/tips-tricks.md, openvpn/ovpn/configure-openvpn.sh
At some point very recently something broke for users where unzip does not function anymore.  I'm wondering if it has to do with the ZIP function on Github changing.  
At any rate, I hacked up the script to use GIT CLONE now and it works on my test build of 4.x.
Cite issues:  https://github.com/haugene/docker-transmission-openvpn/issues/2565
=> OVPN script fix for for 4.x branch 

Dockerfile, docs/config-options.md, transmission/start.sh
This PR packages the open-source web UI [Transmissionic](https://github.com/6c65726f79/Transmissionic) as part of the Docker image. The Transmissionic project has 233 stars on GitHub at the time of writing, has received a commit in the last 30 days and describes itself as follows:
> Transmissionic is a free multi-platform remote for Transmission Daemon built with [Ionic](https://ionicframework.com/) and [Vue.js](https://vuejs.org/).
> It can be used as [Web Interface](https://github.com/transmission/transmission/wiki/Web-Interface), Android/iOS app and Windows/Linux/macOS program.
This project already includes several choices for web UIs. I feel that this particular web UI ought to be included as part of the official Docker image for the following reasons:
- It has a polished user …
=> Add Transmissionic Web UI & New Documentation

privoxy/scripts/start.sh, scripts/healthcheck.sh
```txt
I was having trouble with the privoxy running on a diff IP than what eth0 was reporting. 
In discovery, I noted that there were a couple of problems preventing the healthcheck 
mechanism from automatically fixing things.
These changes are intended to allow healthcheck.sh to successfully get
privoxy running again on correct eth0 IP.
```
None
=> Privoxy eth0 fixes, healthcheck comparison tweak and start.sh update

openvpn/start.sh
```txt
<placeholder>
```
```txt
This pull request fixes #2255. Without that pull request you cannot start app with random ports enabled.
```
- This PR fixes or closes issue: fixes #2255
- This PR is related to issue: -
- Link to documentation updated (if done separately): -
=> Fix problem with enabled UFW with Random Ports

.github/workflows/image-build-template-workflow.yml, Dockerfile, openvpn/start.sh, privoxy/scripts/start.sh, scripts/healthcheck.sh, transmission/start.sh, transmission/userSetup.sh
```txt
<placeholder>
```
```txt
<placeholder>
```
=> update focal branch with dev fixes

.github/workflows/image-build-template-workflow.yml, Dockerfile, docs/config-options.md, openvpn/fetch-external-configs.sh, openvpn/ovpn/configure-openvpn.sh, openvpn/start.sh, privoxy/scripts/start.sh, scripts/healthcheck.sh, transmission/start.sh, transmission/userSetup.sh
```txt
<placeholder>
```
```txt
<placeholder>
```
=> Update main to dev

openvpn/start.sh
Due to non-support of this in latest openvpn it is removed..
```txt
<placeholder>
```
```txt
<placeholder>
```
- This PR fixes or closes issue: ```fixes #2697 ```
=> Remove script_security

docs/provider-specific.md
This is documentation for custom protonvpn configuration. If not appropriate here just close it.
```txt
<placeholder>
```
```txt
<placeholder>
```
- [ x] Documentation added/updated
=> added protonvpn documentation

scripts/healthcheck.sh
nslookup checks for IPv4 and IPv6 records in a single call by default. If either returns an explicit lookup error, healthcheck.sh will report a failure. If the upstream server is rejecting certain requests based on type, such as NordVPN filtering IPv6, healthcheck.sh may never be able to report healthy. Resolve by checking both a and aaaa records separately and only return a failure if both fail.
no
nslookup checks for IPv4 and IPv6 records in a single call by default. If either returns an explicit lookup error, healthcheck.sh will report a failure. If the upstream server is rejecting certain requests based on type, such as NordVPN filtering IPv6, healthcheck.sh may never be able to report healthy. Resolve by checking both a and aaaa records separately and only return a failure if both …
=> Check IPv4 and IPv6 DNS records separately during health check

.github/workflows/docker-transmission-builds.yml
```txt
add quotes to fix file detection for on push trigger
```
=> fix: version file path

openvpn/start.sh
```txt
<placeholder>
```
```txt
Fixes #2874, I think.
The main goal is for the container to not copy the credentials when they're provided via docker secrets as it makes secrets available, bypassing the concept of the secrets.
```
- This PR fixes or closes issue: fixes #2874 
I hope adding this section won't break anything and that everything else was filled correctly 🙏.
I don't know if the change from plain text to a symlink file when using secrets should be documented, if so I'll add it.
This config has been tested locally with
```yaml
secrets:
openvpn_creds:
file: …
```
=> use symlink instead of copy for credentials when using secrets

run-container/index.html
Added a short example to explain what should actually be set as a OPENVPN_CONFIG variable. 
Technical deep dive is great and interesting, but should come later. The most needed basic information to use the parameter should come first, further explanation should come afterwards.
Bit of background/explanation: I was so confused by what to put in the CONFIG variable that I messed around with a manual ovpn instead. Judging by #2408 I'm not the only one. I realize the same explanation as in the issue is present in this wiki page, but it's far down, and opening the github page is much quicker and easier imo. (If you're in the docs you already have a browser open, but one might configure the container through portainer instead of a terminal/ssh connection)
```txt
<placeholder>
```
```txt …
```
=> Update run-container to include short example for config
